#!/usr/bin/env bash

RUNUSER=`id -nu`

if [ "$RUNUSER" != "root" ]   
    then
    echo "This script must be executed as root"
    exit 1
else
	 
	 cp -Rv ../ezhuthani/ /usr/share/
	 mv -v /usr/share/ezhuthani/ezhuthani.run /usr/bin/ezhuthani
	 cp -v /usr/share/ezhuthani/ezhuthani.desktop /usr/share/applications
	 echo "------------------------------------------------------------------------"
	 echo "************************************************************************"
	 echo "------------------------------------------------------------------------"
	 echo "ezhuthani is successfully installed under /usr/share/ezhuthani"
	 echo "To run type the command 'ezhuthani' or 'sudo ezhuthani'"
fi
